#配置数据源
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/ssm_del?useUnicode=true&characterEncoding=utf8
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver

# MyBatis
mybatis:
    # 配置类型别名
    typeAliasesPackage: com.del.ssm.admin.module.**
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mapper/*.xml
    # 加载全局的配置文件
#    configLocation: classpath:mybatis-config.xml